version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=4femqvbw
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: 4femqvbw
      DB_NAME: postgres
      PORT: 5432
      JWT_SECRET: 07bec3efb9a9bb4a492679fde4ba61614063db260b101e8c925f75f51e6bc38b
    ports:
      - 8080:8080
    volumes:
      - .:/backend
    depends_on:
      postgres:
        condition: service_healthy